### ISSUE TITLE
After upgrade to v2.0.0 Wapy is not able to start/function

### ISSUE THREAD

**Issue by TheSander562** [meceware/wapy.dev#96]
Dear,

After following the migration guide, i think i am missing a step somewhere.
Since i am not able to login anymore and my container has the following logs:
```
npm notice New patch version of npm available! 11.6.1 -> 11.6.4
npm notice Changelog: https://github.com/npm/cli/releases/tag/v11.6.4
npm notice To update run: npm install -g npm@11.6.4
npm notice
Deploying database migrations...
Prisma schema loaded from prisma/schema.prisma
Error: Prisma schema validation - (get-config wasm)
Error code: P1012
error: The datasource property `url` is no longer supported in schema files. Move connection URLs for Migrate to `prisma.config.ts` and pass either `adapter` for a direct database connection or `accelerateUrl` for Accelerate to the `PrismaClient` constructor. See https://pris.ly/d/config-datasource and https://pris.ly/d/prisma7-client-config
  -->  prisma/schema.prisma:9
   | 
 8 |   provider = "postgresql"
 9 |   url      = env("DATABASE_URL")
   | 
Validation Error Count: 1
[Context: getConfig]
Prisma CLI Version : 7.0.1
Running server...
   ▲ Next.js 16.0.1
   - Local:        http://localhost:3000
   - Network:      http://0.0.0.0:3000
 ✓ Starting...
 ✓ Ready in 73ms
prisma:error 
Invalid `prisma.subscription.findMany()` invocation:
The column `(not available)` does not exist in the current database.
Error [PrismaClientKnownRequestError]: 
Invalid `prisma.subscription.findMany()` invocation:
The column `(not available)` does not exist in the current database.
    at async _ (.next/server/chunks/_cc5f902f._.js:42:3014)
    at async f (.next/server/chunks/_cc5f902f._.js:42:9212) {
  code: 'P2022',
  meta: [Object],
  clientVersion: '6.19.0'
}
prisma:error 
Invalid `prisma.subscription.findMany()` invocation:
The column `(not available)` does not exist in the current database.
Error [PrismaClientKnownRequestError]: 
Invalid `prisma.subscription.findMany()` invocation:
The column `(not available)` does not exist in the current database.
    at async _ (.next/server/chunks/_cc5f902f._.js:42:3014)
    at async f (.next/server/chunks/_cc5f902f._.js:42:9212) {
  code: 'P2022',
  meta: [Object],
  clientVersion: '6.19.0'
}
```

**Comment by TheSander562** [comment]
And not sure if i can re-use this issue but there seems to be an issue with the new BetterAuth and generic OAuth:
https://www.better-auth.com/docs/plugins/generic-oauth

It seems the scope is limited by default to oauth, but your application is expecting email: 
Better Auth Error
We encountered an issue while processing your request. Please try again or contact the application owner if the problem persists.

[Return to Application](https://betalingen.sanderlambrechts.nl/)
Error Code: email_is_missing

-- Authelia logging:
```
time="2025-11-30T02:32:28+01:00" level=error msg="User Info Request with id '92d793db-884a-455a-8274-c63fadb1ecb9' on client with id 'wapydev' failed with error: bearer authorization failed as the Access Token was not granted the appropriate scope" method=GET path=/api/oidc/userinfo remote_ip=172.16.4.1
```
--
So i think we need to add scopes in this config/line (can be an ENV variable like the other config):
https://github.com/meceware/wapy.dev/blob/main/src/lib/auth.js#L134
Something like:
    scope=["openid", "profile", "email"]

**Comment by meceware** [comment]
Hey, thanks for the logs, very helpful! 

The first error seems to be the migrations is not applied to the database so most probably following errors are because of that. 

I couldn't reproduce the issue locally though, so can I get your help to solve this? I will give instructions at the end of this message, assuming you are using prod docker container.

Can you also check if have any errors or warnings on the database container?

For Authelia, good idea to be an env actually. But I don't know if the system would work without email, as I always assumed the email would be there. I’ll test a no-email setup when I have some time, if you can help with the verification, that would speed things up. I can provide test containers :)


```bash
# Enter docker container sh
docker exec -it wapydev-app sh

# Create the file
touch prisma.config.js
# Edit the file
vi prisma.config.js
# Type i to go into edit mode

# Copy the content of prisma.config.js
# https://github.com/meceware/wapy.dev/blob/main/prisma.config.js
# Go back to the terminal
# Paste, most probably with ctrl+alt+v

# Save the file by pressing these charachters via keyboard in order Esc  : w q
# Press enter, make sure the content is there
cat prisma.config.js

# Reboot the container
# If the same error, let's move the file to the prisma folder and try again
mv prisma.config.js prisma/
# and reboot the container again
```

If you need, I can create test containers for you to try if it's easier. Let me know what you think.

**Comment by TheSander562** [comment]
> Hey, thanks for the logs, very helpful!
> 
> The first error seems to be the migrations is not applied to the database so most probably following errors are because of that.
> 
So what I did to solve it is use your dev branch. Because v2 doesn’t have prisma as dependency it is installing version 7 which is not working. 
So after installing version 6 in the container and running the prisma migrations the application itself is working again.

Let me know how I can help with the authentication part.
I can setup some test containers if still needed.

Kind regards

**Comment by meceware** [comment]
> So what I did to solve it is use your dev branch. Because v2 doesn’t have prisma as dependency it is installing version 7 which is not working.

Aha, interesting! Thanks for the heads up, I prepared migration to v7 but forgot the change the dependencies on the release, so I added it to dev branch right after the release, thinking I'd release it after some tests. I’ll publish it as soon as I wrap up some tests.

I'll also send you something soon for you to test, thank you very much for your help.

**Comment by meceware** [comment]
I added a `.env` variable called `GENERIC_AUTH_SCOPE` that accepts space-separated values. Add this to your `.env` file as

```
GENERIC_AUTH_SCOPE=openid profile
```
assuming email scope is omitted. Most probably you will see some errors on various points. I checked the code and I don't think the system would work without emails. Feel free to try it and let me know how it behaves, which also should solve the other issue since it's built on dev branch.

Please use dev tag on docker: `ghcr.io/meceware/wapy.dev:dev`

**Comment by TheSander562** [comment]
Hm with that branch I am still getting the following issue:
```
npm warn exec The following package was not found and will be installed: prisma@7.0.1
Error: Prisma schema validation - (get-config wasm)
Error code: P1012
error: The datasource property `url` is no longer supported in schema files. Move connection URLs for Migrate to `prisma.config.ts` and pass either `adapter` for a direct database connection or `accelerateUrl` for Accelerate to the `PrismaClient` constructor. See https://pris.ly/d/config-datasource and https://pris.ly/d/prisma7-client-config
  -->  prisma/schema.prisma:9
   | 
 8 |   provider = "postgresql"
 9 |   url      = env("DATABASE_URL")
   | 
Validation Error Count: 1
[Context: getConfig]
Prisma CLI Version : 7.0.1
npm notice
npm notice New patch version of npm available! 11.6.2 -> 11.6.4
npm notice Changelog: https://github.com/npm/cli/releases/tag/v11.6.4
npm notice To update run: npm install -g npm@11.6.4
npm notice
Deploying database migrations...
Prisma schema loaded from prisma/schema.prisma
Error: Prisma schema validation - (get-config wasm)
Error code: P1012
error: The datasource property `url` is no longer supported in schema files. Move connection URLs for Migrate to `prisma.config.ts` and pass either `adapter` for a direct database connection or `accelerateUrl` for Accelerate to the `PrismaClient` constructor. See https://pris.ly/d/config-datasource and https://pris.ly/d/prisma7-client-config
  -->  prisma/schema.prisma:9
   | 
 8 |   provider = "postgresql"
 9 |   url      = env("DATABASE_URL")
   | 
Validation Error Count: 1
[Context: getConfig]
```

For the authelia part not sure if we can add more debugging to see more errors/issues since from authelia I now see the following:
`User Info Request with id '2740a245-bb43-4f82-85e7-0436cb323650' on client with id 'wapydev' failed with error: bearer authorization failed as the Access Token was not granted the appropriate scope" method=GET path=/api/oidc/userinfo remote_ip=172.16.4.1`
And from Wapy I am getting the email missing since probably it is not finding anything since it doesn’t receive any token.

**Comment by TheSander562** [comment]
This is my authelia config part:
```
      - client_id: 'wapydev'
        client_name: 'WapyDev Login'
        client_secret: '$pbkdf2-sha512$310000$blabla'
        sector_identifier_uri: ''
        public: false
        redirect_uris:
          - 'https://payments.domain.nl/api/auth/oauth2/callback/authelia'
        audience: []
        scopes:
          - 'openid'
          - 'offline_access'
          - 'groups'
          - 'profile'
          - 'email'
        grant_types:
          - 'refresh_token'
          - 'authorization_code'
        response_types:
          - 'code'
          - 'token'
          - 'id_token'
        response_modes:
          - 'form_post'
          - 'query'
          - 'fragment'
        authorization_policy: 'two_factor'
        consent_mode: 'implicit'
        token_endpoint_auth_method: 'client_secret_post'
```

**Comment by meceware** [comment]
Thank you very much for the test, I am hands full these days but I will take a look at the prisma issue soon since it's a blocker for the project. 

To be honest I've not used Authelia before. I will try to setup a local setup for testing and use your parameters, thanks for these, and see if it would work. But from what I see, bearer token is not received from authelia, most probably related to email or some other scope. I need to dive in to it to understand more.

**Comment by meceware** [comment]
Hey, I created a new version that fixes these issues as well as includes the scope .env parameter. I'm hoping you can test with it

**Comment by TheSander562** [comment]
```
Loaded Prisma config from prisma.config.js.
Database schema is up to date, skipping migration...
Running server...
   ▲ Next.js 16.0.7
   - Local:         http://localhost:3000
   - Network:       http://0.0.0.0:3000
 ✓ Starting...
 ✓ Ready in 67ms
```

The issue with Prisma is fixed indeed in latest version 🥳 
Thank you.

Still checking the anthelia issue

**Comment by TheSander562** [comment]
I have fixed the issue, will adjust my MR a bit but i tested it in my dev environment and looks like scope needed to be scopes so now its working:
`https://betalingen.domain.nl/api/auth/oauth2/callback/authelia?code=authelia_ac_X6pJROgzo455FMZ0x3SWaMnesPVsM8Ndy1Xmybb6BoY.ZIMvv-vq45Wg1RaS3bSiomtlnv-JKMmXWEj-0GAqib8&iss=https%3A%2F%2Fauth.domain.nl&scope=openid+profile+email&state=gxzbjv9fZUTerEzu5hHiTVHhMWxU6_de
`
As you can see the scopes are now added
MR: https://github.com/meceware/wapy.dev/pull/100

Maybe first in dev and then when you confirm your checks also still works then we can merge into master

**Comment by meceware** [comment]
Thank you, the patch looks good and `scopes` keyword is matching with the [better auth documentation](https://www.better-auth.com/docs/authentication/other-social-providers).

I tested authentik with `openid profile email` and works without problem. I've merge it with dev and continue to merge it to mainline if you've completed your tests.

**Comment by TheSander562** [comment]
> Thank you, the patch looks good and `scopes` keyword is matching with the [better auth documentation](https://www.better-auth.com/docs/authentication/other-social-providers).
> 
> I tested authentik with `openid profile email` and works without problem. I've merge it with dev and continue to merge it to mainline if you've completed your tests.

Thank you for looking into it but I don’t see it yet merged in DEV to test with my existing user and setup

**Comment by meceware** [comment]
I also checked the `email_missing` error and generated the error via authentik thanks to your patch, it looks like the system requires at least `profile email` scopes which includes name and email definitely.

**Comment by meceware** [comment]
> Thank you for looking into it but I don’t see it yet merged in DEV to test with my existing user and setup

Sorry, I've been playing with it a bit more :)

**Comment by TheSander562** [comment]
Looks like all is working perfectly and logged in my account through the OAuth login with Authelia.
Thanks for your time.

**Comment by fsmeets84** [comment]
I'm using PocketID as auth provider but still can't login with OIDC.
When logging in, everything seems to go fine but it then redirects back to the main page.
In the log it shows the following error:

```
2025-12-11T07:42:03.789Z ERROR [Better Auth]:  {
  error: 'Invalid code verifier',
  status: 400,
  statusText: 'Bad Request'
}
```

**Comment by meceware** [comment]
@fsmeets84 are you using a proxy in between? This is most likely a configuration issue, either with redirect URI, or a proxy configuration issue. I've not used PocketID myself before there are issues in better-auth for similar things. ([Example](https://github.com/sevensolutions/traefik-oidc-auth/issues/170))
